# Generated by Django 4.1.4 on 2023-02-01 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hr', models.BooleanField(default=False)),
                ('is_employe', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('apply_for', models.CharField(choices=[('Hr', 'HR'), ('manager', 'Manager'), ('Employees', 'employe')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
