# Generated by Django 4.1.4 on 2023-02-02 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managment', '0004_eplo_project_added_by_remove_eplo_project_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eplo_project',
            name='RM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
