# Generated by Django 4.1.4 on 2023-02-02 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managment', '0007_leave_manag_hr_approved_leave_manag_hr_reject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_manag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
