# Generated by Django 4.1.4 on 2023-02-03 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managment', '0008_alter_leave_manag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='allocated_proj',
            field=models.CharField(default='nothing', max_length=50),
        ),
        migrations.RemoveField(
            model_name='eplo_project',
            name='user',
        ),
        migrations.AddField(
            model_name='eplo_project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='us', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
