# Generated by Django 4.1.4 on 2023-02-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0009_profiles_allocated_proj_remove_eplo_project_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eplo_project',
            old_name='user',
            new_name='employes',
        ),
    ]
