# Generated by Django 4.1.4 on 2023-02-03 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managment', '0012_manager_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_employe',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
